import boto3
from moto import mock_aws

from tadween_whisperx.config import (
    AlignmentConfig,
    AppConfig,
    DiarizationConfig,
    JsonRepoConfig,
    LocalInputConfig,
    NormalizerConfig,
    RepoProfiles,
    S3InputConfig,
    S3RepoConfig,
    TranscriptionConfig,
    set_config,
)
from tadween_whisperx.runner import Runner


def test_runner_local_input_json_repo(sample_audio, tmp_path, mock_handlers):  # noqa: ARG001
    repo_path = tmp_path / "json-repo"

    config = AppConfig(
        input=LocalInputConfig(paths=[tmp_path]),
        repo=RepoProfiles(
            active="test", profiles={"test": JsonRepoConfig(path=repo_path)}
        ),
        diarization=DiarizationConfig(enabled=True),
        transcription=TranscriptionConfig(enabled=True),
        alignment=AlignmentConfig(enabled=True),
        normalizer=NormalizerConfig(enabled=True),
        log_level="ERROR",
        core_log_level="ERROR",
    )

    set_config(config)
    runner = Runner(config)
    runner.run()

    # Check if JSON repo has the output
    # The artifact_id is generated by LocalScanner
    # We expect one artifact to be saved.
    assert repo_path.exists()

    # List files in repo
    artifact_dirs = list(repo_path.glob("*"))
    assert len(artifact_dirs) == 1

    # Check if root.json and parts exist in the artifact dir
    artifact_dir = artifact_dirs[0]
    assert (artifact_dir / "root.json").exists()
    assert (artifact_dir / "transcription.json").exists()
    assert (artifact_dir / "diarization.json").exists()
    assert (artifact_dir / "alignment.json").exists()
    assert (artifact_dir / "normalization.json").exists()


@mock_aws
def test_runner_s3_input_s3_repo(mock_handlers, tmp_path):  # noqa: ARG001
    # Setup mock S3
    s3 = boto3.client("s3", region_name="us-east-1")
    input_bucket = "input-bucket"
    repo_bucket = "repo-bucket"
    s3.create_bucket(Bucket=input_bucket)
    s3.create_bucket(Bucket=repo_bucket)

    # Upload a dummy audio file
    s3.put_object(
        Bucket=input_bucket, Key="audio/test.wav", Body=b"dummy audio content"
    )

    config = AppConfig(
        input=S3InputConfig(
            bucket=input_bucket,
            prefix="audio/",
            aws_access_key_id="testing",
            aws_secret_access_key="testing",
            region_name="us-east-1",
            download_path=tmp_path / "downloads",
        ),
        repo=RepoProfiles(
            active="s3-test",
            profiles={
                "s3-test": S3RepoConfig(
                    bucket=repo_bucket,
                    prefix="repo/",
                    aws_access_key_id="testing",
                    aws_secret_access_key="testing",
                    region_name="us-east-1",
                )
            },
        ),
        diarization=DiarizationConfig(enabled=True),
        transcription=TranscriptionConfig(enabled=True),
        alignment=AlignmentConfig(enabled=True),
        normalizer=NormalizerConfig(enabled=True),
        log_level="ERROR",
        core_log_level="ERROR",
    )

    # We need to ensure DownloaderComponent.run uses the mock S3 if it doesn't already
    # S3Scanner and S3Downloader use boto3.

    set_config(config)
    runner = Runner(config)
    runner.run()

    # Check if S3 repo has the output
    response = s3.list_objects_v2(Bucket=repo_bucket, Prefix="repo/")
    assert "Contents" in response
    keys = [obj["Key"] for obj in response["Contents"]]
    assert any(key.endswith("root.json") for key in keys)
    assert any(key.endswith("transcription.bin") for key in keys)
    assert any(key.endswith("diarization.bin") for key in keys)


def test_runner_error_handling(sample_audio, tmp_path, mock_handlers):  # noqa: ARG001
    # Simulate a failure in transcription
    mock_handlers["transcription"].side_effect = RuntimeError("Model failed")

    repo_path = tmp_path / "json-repo-error"
    config = AppConfig(
        input=LocalInputConfig(paths=[tmp_path]),
        repo=RepoProfiles(
            active="test", profiles={"test": JsonRepoConfig(path=repo_path)}
        ),
        transcription=TranscriptionConfig(enabled=True),
        log_level="ERROR",
        core_log_level="ERROR",
    )

    set_config(config)
    runner = Runner(config)
    runner.run()

    # Even if it failed, we want to see how it reacted.
    # Usually, if a stage fails, the artifact might not be saved or saved with error state if supported.
    # tadween-whisperx seems to just log the error and continue if there are more files.

    # Check that stash was cleared
    assert runner.wf.context.state_get("active_stash") == 0
    assert runner.wf.cache.get_bucket("0") is None
